// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Zero Root AI

package unwired

import (
	"bufio"
	"fmt"
	"os"
	"sort"
	"strings"
	"time"
)

// Baseline is the set of tolerated ContentKey values.
type Baseline map[string]bool

// ReadBaseline loads a baseline file. Lines are ContentKey values; a `#` line is
// a comment, which is where the reason for an entry goes.
//
// A missing file is an error rather than an empty baseline. An empty baseline
// tolerates nothing and would fail the whole repo at once, which reads as a
// broken gate; a missing file is a wiring mistake and says so.
func ReadBaseline(path string) (Baseline, error) {
	f, err := os.Open(path) // #nosec G304 -- the path is an operator-supplied flag.
	if err != nil {
		return nil, fmt.Errorf("unwired: baseline %s: %w. Create it with -write", path, err)
	}
	defer func() { _ = f.Close() }()

	out := Baseline{}
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for sc.Scan() {
		line := sc.Text()
		// A trailing "\t# file:line" is the coordinate WriteBaseline adds for a
		// reader's benefit, and it is not part of the key. Keeping it made every
		// entry fail to match its own written form, so a freshly written baseline
		// reported all of its entries as both resolved and new.
		if i := strings.IndexByte(line, '\t'); i >= 0 {
			line = line[:i]
		}
		if i := strings.IndexByte(line, '#'); i >= 0 {
			line = line[:i]
		}
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		out[line] = true
	}
	if err := sc.Err(); err != nil {
		return nil, fmt.Errorf("unwired: read %s: %w", path, err)
	}
	return out, nil
}

// WriteBaseline rewrites the baseline from a run.
//
// Entries are ContentKey values, sorted, one per line. The coordinate is written
// as a trailing comment only: a baseline keyed by file and line needs re-pinning
// every time an unrelated edit shifts a line, which the workspace rule names as
// a defect in the guard rather than in the code.
func WriteBaseline(path string, decls []Decl, res Result) error {
	keys := make([]string, 0, len(decls))
	coords := map[string]string{}
	for _, d := range decls {
		keys = append(keys, d.ContentKey())
		coords[d.ContentKey()] = d.Coord
	}
	sort.Strings(keys)

	var b strings.Builder
	b.WriteString("# unwired baseline: declarations that production code reads nowhere.\n")
	b.WriteString("# Generated by `unwired -write`. Entries are keyed by kind and qualified\n")
	b.WriteString("# name, never by line, so an unrelated edit never needs a re-pin.\n")
	b.WriteString("# The coordinate after each entry is a comment and is not matched.\n")
	b.WriteString("#\n")
	b.WriteString("# This file only shrinks. Adding an entry means accepting a declaration\n")
	b.WriteString("# nothing reads, so put the reason on a # line above it.\n")
	fmt.Fprintf(&b, "#\n# measured %s: %d of %d declarations across %d packages and %d files\n",
		time.Now().UTC().Format("2006-01-02"), len(decls), len(res.Decls), res.Packages, res.Files)
	b.WriteString("\n")
	for _, k := range keys {
		fmt.Fprintf(&b, "%s\t# %s\n", k, coords[k])
	}

	if err := os.WriteFile(path, []byte(b.String()), 0o600); err != nil {
		return fmt.Errorf("unwired: write %s: %w", path, err)
	}
	return nil
}
